[http]
addr = "127.0.0.1"
port = 8080

[mysql]
addr = "127.0.0.1:3306"
username = "user"
password = "123456"

[redis]
addr = "127.0.0.1:6379"
passwd = "myredis"
db = 0

[wxapp]
appid = "wxa36fea40b02677d0"
appsecret = "4cec8431ec6eac438bab553566f4a1d8"

[oss]
accessKeyId = "LTAI32mpHYeNPlyv"
accessKeySecret = "H7yHgJcBr5GOAVLdiPUrhy3UX6zGdw"
bucketName = "wechat-mall-image"